export interface DemoExample {
    textA: string;
    textB: string;
    normalizedTextA?: string;
    normalizedTextB?: string;
    category: string;
    relation: 'very_similar' | 'related' | 'weakly_related' | 'unrelated' | 'opposite';
    explanation: string;
    tags?: string[];
    vectorA?: number[];
    vectorB?: number[];
}

export const rawDemoExamples: DemoExample[] = [
    // === Category: RAG & Vector Search ===
    {
        textA: "RAG",
        textB: "Retrieval-Augmented Generation",
        category: "rag_vector_search",
        relation: "very_similar",
        explanation: "RAG is the standard acronym for Retrieval-Augmented Generation.",
        tags: ["ai", "rag", "retrieval"]
    },
    {
        textA: "vector search",
        textB: "semantic search",
        category: "rag_vector_search",
        relation: "very_similar",
        explanation: "Semantic search uses vector search to find conceptually similar items based on embeddings.",
        tags: ["vector", "search", "nlp"]
    },
    {
        textA: "embedding",
        textB: "vector representation",
        category: "rag_vector_search",
        relation: "very_similar",
        explanation: "An embedding is a vector representation of text in a high-dimensional space.",
        tags: ["embeddings", "math", "ai"]
    },
    {
        textA: "chunking",
        textB: "text splitting",
        category: "rag_vector_search",
        relation: "very_similar",
        explanation: "Chunking and text splitting are terms for dividing documents into smaller, manageable parts for embeddings.",
        tags: ["preprocessing", "rag"]
    },
    {
        textA: "hybrid search",
        textB: "keyword + vector search",
        category: "rag_vector_search",
        relation: "very_similar",
        explanation: "Hybrid search combines classic BM25 keyword matching with vector-based semantic search.",
        tags: ["search", "hybrid", "bm25"]
    },
    {
        textA: "cosine similarity",
        textB: "dot product",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Both are mathematical operations used to measure the alignment and similarity of vectors.",
        tags: ["math", "similarity"]
    },
    {
        textA: "RAG",
        textB: "prompt engineering",
        category: "rag_vector_search",
        relation: "related",
        explanation: "RAG retrieves relevant context to pass into an LLM prompt, making it a form of prompt optimization.",
        tags: ["prompt", "context", "llm"]
    },
    {
        textA: "embeddings",
        textB: "cosine similarity",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Cosine similarity is the standard metric used to compare text embeddings.",
        tags: ["embeddings", "math"]
    },
    {
        textA: "vector database",
        textB: "pinecone",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Pinecone is a dedicated managed service for hosting a vector database.",
        tags: ["db", "pinecone", "cloud"]
    },
    {
        textA: "chunking size",
        textB: "retrieval accuracy",
        category: "rag_vector_search",
        relation: "related",
        explanation: "The chunking size of texts directly affects how relevant and precise the retrieved context is in RAG.",
        tags: ["rag", "tuning"]
    },
    {
        textA: "vector index",
        textB: "HNSW",
        category: "rag_vector_search",
        relation: "related",
        explanation: "HNSW (Hierarchical Navigable Small World) is a popular graph algorithm used to build a vector index.",
        tags: ["algorithms", "hnsw"]
    },
    {
        textA: "Pinecone",
        textB: "Milvus",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Pinecone and Milvus are both well-known vector databases, though Milvus is open-source.",
        tags: ["databases", "options"]
    },
    {
        textA: "embeddings",
        textB: "neural network",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Text embeddings are generated by the intermediate layers of a trained neural network.",
        tags: ["ai", "deep_learning"]
    },
    {
        textA: "metadata filtering",
        textB: "vector search",
        category: "rag_vector_search",
        relation: "related",
        explanation: "Metadata filtering is used alongside vector search to restrict search space based on attributes like dates or tags.",
        tags: ["filtering", "search"]
    },
    {
        textA: "RAG",
        textB: "SQL database",
        category: "rag_vector_search",
        relation: "related",
        explanation: "A RAG system retrieves data, which can come from an SQL database, to feed into an LLM.",
        tags: ["databases", "rag"]
    },
    {
        textA: "vector database",
        textB: "relational database",
        category: "rag_vector_search",
        relation: "weakly_related",
        explanation: "Both are databases, but relational databases store structured rows, while vector databases index high-dimensional arrays.",
        tags: ["databases", "comparison"]
    },
    {
        textA: "vector embedding",
        textB: "file system",
        category: "rag_vector_search",
        relation: "weakly_related",
        explanation: "Both store data, but a file system organizes files hierarchically, while embeddings map concepts mathematically.",
        tags: ["storage"]
    },
    {
        textA: "dense vector",
        textB: "sparse vector",
        category: "rag_vector_search",
        relation: "opposite",
        explanation: "Dense vectors contain mostly non-zero floating values, whereas sparse vectors contain mostly zeros.",
        tags: ["vectors", "math"]
    },
    {
        textA: "keyword search",
        textB: "vector search",
        category: "rag_vector_search",
        relation: "opposite",
        explanation: "Keyword search matches exact words (lexical), while vector search matches conceptual meanings (semantic).",
        tags: ["search", "lexical", "semantic"]
    },
    {
        textA: "retrieval",
        textB: "generation",
        category: "rag_vector_search",
        relation: "opposite",
        explanation: "Retrieval fetches pre-existing documents, while generation creates new language tokens.",
        tags: ["rag", "stages"]
    },
    {
        textA: "vector database",
        textB: "toothbrush",
        category: "rag_vector_search",
        relation: "unrelated",
        explanation: "A vector database is software for index storage, while a toothbrush is a tool for personal hygiene.",
        tags: ["mismatch"]
    },
    {
        textA: "retrieval augmented generation",
        textB: "pizza delivery",
        category: "rag_vector_search",
        relation: "unrelated",
        explanation: "Retrieval augmented generation is an AI technique; pizza delivery is a food transport service.",
        tags: ["mismatch"]
    },

    // === Category: Software Development ===
    {
        textA: "software engineer",
        textB: "developer",
        category: "software_development",
        relation: "very_similar",
        explanation: "Both terms describe a professional who designs and builds software applications.",
        tags: ["career", "roles"]
    },
    {
        textA: "coder",
        textB: "programmer",
        category: "software_development",
        relation: "very_similar",
        explanation: "These words are widely used as synonyms for someone who writes source code.",
        tags: ["career"]
    },
    {
        textA: "bug",
        textB: "software defect",
        category: "software_development",
        relation: "very_similar",
        explanation: "A bug is an informal term for a software defect or flaw that causes incorrect behavior.",
        tags: ["debugging"]
    },
    {
        textA: "refactoring",
        textB: "code cleanup",
        category: "software_development",
        relation: "very_similar",
        explanation: "Refactoring is modifying existing code structure to clean it up without changing external behavior.",
        tags: ["maintenance"]
    },
    {
        textA: "CI/CD",
        textB: "deployment pipeline",
        category: "software_development",
        relation: "very_similar",
        explanation: "CI/CD (Continuous Integration/Continuous Deployment) is the automation of a deployment pipeline.",
        tags: ["devops", "ci-cd"]
    },
    {
        textA: "compiler",
        textB: "interpreter",
        category: "software_development",
        relation: "related",
        explanation: "Both process high-level source code, but a compiler translates it beforehand, while an interpreter runs it on the fly.",
        tags: ["languages"]
    },
    {
        textA: "Git",
        textB: "GitHub",
        category: "software_development",
        relation: "related",
        explanation: "Git is a local version control tool, whereas GitHub is a cloud service that hosts Git repositories.",
        tags: ["tools", "git"]
    },
    {
        textA: "unit test",
        textB: "integration test",
        category: "software_development",
        relation: "related",
        explanation: "Both are automated tests; unit tests isolate individual functions, while integration tests verify components together.",
        tags: ["testing"]
    },
    {
        textA: "library",
        textB: "framework",
        category: "software_development",
        relation: "related",
        explanation: "Your code calls a library, while a framework imposes control flow and calls your code (inversion of control).",
        tags: ["architecture"]
    },
    {
        textA: "HTML",
        textB: "CSS",
        category: "software_development",
        relation: "related",
        explanation: "HTML defines the structured content of a webpage, while CSS handles its visual styling.",
        tags: ["frontend", "web"]
    },
    {
        textA: "JavaScript",
        textB: "TypeScript",
        category: "software_development",
        relation: "related",
        explanation: "TypeScript is a typed superset of JavaScript that compiles down to plain JavaScript.",
        tags: ["languages", "frontend"]
    },
    {
        textA: "JSON",
        textB: "XML",
        category: "software_development",
        relation: "related",
        explanation: "Both are structured text formats used for serializing and exchanging data across networks.",
        tags: ["formats", "api"]
    },
    {
        textA: "API",
        textB: "web service",
        category: "software_development",
        relation: "related",
        explanation: "An API is a programming interface, and web services are network-accessible APIs.",
        tags: ["web", "api"]
    },
    {
        textA: "class",
        textB: "object",
        category: "software_development",
        relation: "related",
        explanation: "A class acts as a template or blueprint, and an object is an instantiated copy of that class in memory.",
        tags: ["oop"]
    },
    {
        textA: "IDE",
        textB: "text editor",
        category: "software_development",
        relation: "related",
        explanation: "An IDE is a specialized text editor bundled with compilers, debuggers, and autocompletion tools.",
        tags: ["tools"]
    },
    {
        textA: "laptop",
        textB: "programming",
        category: "software_development",
        relation: "weakly_related",
        explanation: "Laptops are the physical hardware often used to do programming, though they are used for many other tasks.",
        tags: ["hardware"]
    },
    {
        textA: "frontend",
        textB: "backend",
        category: "software_development",
        relation: "opposite",
        explanation: "Frontend refers to user interface client code; backend refers to server, logic, and database operations.",
        tags: ["architecture", "web"]
    },
    {
        textA: "source code",
        textB: "binary code",
        category: "software_development",
        relation: "opposite",
        explanation: "Source code is human-readable instructions; binary code is machine-executable 1s and 0s.",
        tags: ["compilation"]
    },
    {
        textA: "monolith",
        textB: "microservices",
        category: "software_development",
        relation: "opposite",
        explanation: "A monolith is a single tightly-coupled application; microservices are divided into isolated, distributed services.",
        tags: ["architecture"]
    },
    {
        textA: "synchronous",
        textB: "asynchronous",
        category: "software_development",
        relation: "opposite",
        explanation: "Synchronous operations block execution until complete; asynchronous operations run in the background.",
        tags: ["async", "concurrency"]
    },
    {
        textA: "stack",
        textB: "queue",
        category: "software_development",
        relation: "opposite",
        explanation: "A stack operates on Last-In-First-Out (LIFO), whereas a queue operates on First-In-First-Out (FIFO).",
        tags: ["data_structures"]
    },
    {
        textA: "beach",
        textB: "Java exception",
        category: "software_development",
        relation: "unrelated",
        explanation: "A beach is a sandy shore; a Java exception is a runtime error thrown in Java programs.",
        tags: ["mismatch"]
    },

    // === Category: Databases ===
    {
        textA: "database",
        textB: "data storage",
        category: "databases",
        relation: "very_similar",
        explanation: "A database is a specialized software system for structured data storage and retrieval.",
        tags: ["db"]
    },
    {
        textA: "NoSQL",
        textB: "non-relational database",
        category: "databases",
        relation: "very_similar",
        explanation: "NoSQL is the standard synonym for a non-relational database system.",
        tags: ["nosql", "db"]
    },
    {
        textA: "MongoDB",
        textB: "document database",
        category: "databases",
        relation: "very_similar",
        explanation: "MongoDB is a leading implementation of a document-oriented NoSQL database.",
        tags: ["mongodb", "nosql"]
    },
    {
        textA: "PostgreSQL",
        textB: "relational database",
        category: "databases",
        relation: "very_similar",
        explanation: "PostgreSQL is a powerful, open-source object-relational SQL database.",
        tags: ["postgres", "sql"]
    },
    {
        textA: "Redis",
        textB: "in-memory cache",
        category: "databases",
        relation: "very_similar",
        explanation: "Redis is an in-memory key-value data structure store used primarily as a cache.",
        tags: ["redis", "cache"]
    },
    {
        textA: "SQL",
        textB: "relational database",
        category: "databases",
        relation: "related",
        explanation: "SQL (Structured Query Language) is the language used to manage relational databases.",
        tags: ["sql", "queries"]
    },
    {
        textA: "database index",
        textB: "search optimization",
        category: "databases",
        relation: "related",
        explanation: "A database index is a data structure built on columns to perform search optimization.",
        tags: ["indexing", "performance"]
    },
    {
        textA: "primary key",
        textB: "foreign key",
        category: "databases",
        relation: "related",
        explanation: "Primary keys uniquely identify records, while foreign keys establish relationships to other tables.",
        tags: ["schema"]
    },
    {
        textA: "ACID",
        textB: "database transactions",
        category: "databases",
        relation: "related",
        explanation: "ACID properties define the reliability guarantees of database transactions.",
        tags: ["reliability"]
    },
    {
        textA: "read replica",
        textB: "write database",
        category: "databases",
        relation: "related",
        explanation: "Read replicas are duplicated instances that scale query reading off the main write database.",
        tags: ["scaling"]
    },
    {
        textA: "data migration",
        textB: "schema update",
        category: "databases",
        relation: "related",
        explanation: "A data migration script updates the schema definition and shape of a database.",
        tags: ["migrations"]
    },
    {
        textA: "transaction",
        textB: "rollback",
        category: "databases",
        relation: "related",
        explanation: "A transaction groups changes, and a rollback cancels them if any error occurs.",
        tags: ["transactions"]
    },
    {
        textA: "normalization",
        textB: "denormalization",
        category: "databases",
        relation: "opposite",
        explanation: "Normalization splits tables to eliminate redundancy; denormalization merges tables to speed up reads.",
        tags: ["db_design"]
    },
    {
        textA: "row",
        textB: "column",
        category: "databases",
        relation: "opposite",
        explanation: "A row represents an individual record, whereas a column represents an attribute field.",
        tags: ["table"]
    },
    {
        textA: "OLAP",
        textB: "OLTP",
        category: "databases",
        relation: "opposite",
        explanation: "OLAP is optimized for complex data analysis queries; OLTP is optimized for fast transactional operations.",
        tags: ["analytics", "transactions"]
    },
    {
        textA: "football",
        textB: "SQL query",
        category: "databases",
        relation: "unrelated",
        explanation: "Football is an athletic team sport; an SQL query is a text statement executed by a database engine.",
        tags: ["mismatch"]
    },

    // === Category: Cloud & DevOps ===
    {
        textA: "AWS",
        textB: "Amazon Web Services",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "AWS is the three-letter acronym for Amazon Web Services.",
        tags: ["cloud", "aws"]
    },
    {
        textA: "Kubernetes",
        textB: "container orchestration",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "Kubernetes is the industry standard tool used for container orchestration.",
        tags: ["k8s", "orchestration"]
    },
    {
        textA: "serverless",
        textB: "FaaS",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "Serverless architectures compile functions triggered by events, often called Function-as-a-Service.",
        tags: ["serverless", "faas"]
    },
    {
        textA: "load balancer",
        textB: "traffic distribution",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "A load balancer distributes incoming network traffic across multiple servers.",
        tags: ["networking"]
    },
    {
        textA: "terraform",
        textB: "infrastructure as code",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "Terraform is a widely adopted framework for writing infrastructure as code.",
        tags: ["iac", "terraform"]
    },
    {
        textA: "CDN",
        textB: "Content Delivery Network",
        category: "cloud_devops",
        relation: "very_similar",
        explanation: "CDN is the acronym for Content Delivery Network.",
        tags: ["caching", "cdn"]
    },
    {
        textA: "Docker",
        textB: "containerization",
        category: "cloud_devops",
        relation: "related",
        explanation: "Docker popularized the isolation of application environments called containerization.",
        tags: ["docker", "containers"]
    },
    {
        textA: "monitoring",
        textB: "logging",
        category: "cloud_devops",
        relation: "related",
        explanation: "Monitoring tracks high-level system metrics, while logging outputs granular event details.",
        tags: ["observability"]
    },
    {
        textA: "CI/CD",
        textB: "Jenkins",
        category: "cloud_devops",
        relation: "related",
        explanation: "Jenkins is one of the oldest and most common open-source tools for CI/CD automation.",
        tags: ["tools"]
    },
    {
        textA: "IP address",
        textB: "domain name",
        category: "cloud_devops",
        relation: "related",
        explanation: "A domain name is a human-friendly string that DNS resolves to a machine IP address.",
        tags: ["networking"]
    },
    {
        textA: "virtual machine",
        textB: "container",
        category: "cloud_devops",
        relation: "related",
        explanation: "Both isolate runtimes; VMs run full guest operating systems, while containers share the host kernel.",
        tags: ["virtualization"]
    },
    {
        textA: "train",
        textB: "commute",
        category: "cloud_devops",
        relation: "weakly_related",
        explanation: "Trains are a form of transport often taken to commute to a workplace.",
        tags: ["travel"]
    },
    {
        textA: "cloud computing",
        textB: "on-premise server",
        category: "cloud_devops",
        relation: "opposite",
        explanation: "Cloud computing rents remote infrastructure; on-premise uses physical servers in your own facility.",
        tags: ["hosting"]
    },
    {
        textA: "uptime",
        textB: "downtime",
        category: "cloud_devops",
        relation: "opposite",
        explanation: "Uptime is the duration a service is active; downtime is the period of service disruption.",
        tags: ["metrics"]
    },
    {
        textA: "private cloud",
        textB: "public cloud",
        category: "cloud_devops",
        relation: "opposite",
        explanation: "Private cloud is dedicated to a single client; public cloud is shared across multiple tenants.",
        tags: ["cloud"]
    },
    {
        textA: "autoscaling",
        textB: "manual scaling",
        category: "cloud_devops",
        relation: "opposite",
        explanation: "Autoscaling dynamically provisions resources based on load, while manual scaling requires operator input.",
        tags: ["scaling"]
    },
    {
        textA: "banana",
        textB: "cloud deployment",
        category: "cloud_devops",
        relation: "unrelated",
        explanation: "A banana is an edible yellow fruit; cloud deployment is the rollout of server applications.",
        tags: ["mismatch"]
    },

    // === Category: AI Concepts ===
    {
        textA: "AI",
        textB: "artificial intelligence",
        category: "ai_concepts",
        relation: "very_similar",
        explanation: "AI stands for artificial intelligence.",
        tags: ["ai"]
    },
    {
        textA: "LLM",
        textB: "large language model",
        category: "ai_concepts",
        relation: "very_similar",
        explanation: "LLM is the common acronym for large language model.",
        tags: ["llm", "ai"]
    },
    {
        textA: "GPT",
        textB: "Generative Pre-trained Transformer",
        category: "ai_concepts",
        relation: "very_similar",
        explanation: "GPT stands for Generative Pre-trained Transformer, an LLM architecture.",
        tags: ["gpt", "transformer"]
    },
    {
        textA: "agent",
        textB: "autonomous LLM system",
        category: "ai_concepts",
        relation: "very_similar",
        explanation: "An AI agent is an autonomous LLM system that can call tools and execute tasks.",
        tags: ["agents", "llm"]
    },
    {
        textA: "tokens",
        textB: "word pieces",
        category: "ai_concepts",
        relation: "very_similar",
        explanation: "Tokens are the character chunks or word pieces processed by language models.",
        tags: ["tokenization"]
    },
    {
        textA: "machine learning",
        textB: "deep learning",
        category: "ai_concepts",
        relation: "related",
        explanation: "Deep learning is a specific subset of machine learning using multi-layered neural networks.",
        tags: ["ml", "dl"]
    },
    {
        textA: "neural network",
        textB: "deep learning",
        category: "ai_concepts",
        relation: "related",
        explanation: "Neural networks are the mathematical structures that power deep learning models.",
        tags: ["architecture"]
    },
    {
        textA: "prompt engineering",
        textB: "context input",
        category: "ai_concepts",
        relation: "related",
        explanation: "Prompt engineering is the design of context input strings to get specific outputs from LLMs.",
        tags: ["prompt"]
    },
    {
        textA: "hallucination",
        textB: "factual error",
        category: "ai_concepts",
        relation: "related",
        explanation: "An LLM hallucination is a type of conceptual or factual error generated by generative models.",
        tags: ["errors"]
    },
    {
        textA: "fine-tuning",
        textB: "transfer learning",
        category: "ai_concepts",
        relation: "related",
        explanation: "Fine-tuning is a technique of transfer learning where a pre-trained model is adapted to a narrower task.",
        tags: ["training"]
    },
    {
        textA: "temperature",
        textB: "creativity parameter",
        category: "ai_concepts",
        relation: "related",
        explanation: "Temperature acts as a creativity parameter that controls token selection randomness in LLM inference.",
        tags: ["parameters"]
    },
    {
        textA: "book",
        textB: "learning",
        category: "ai_concepts",
        relation: "weakly_related",
        explanation: "Books are static objects used for learning, though learning is a wider cognitive process.",
        tags: ["education"]
    },
    {
        textA: "supervised learning",
        textB: "unsupervised learning",
        category: "ai_concepts",
        relation: "opposite",
        explanation: "Supervised learning trains models on labeled data; unsupervised learning works with unlabeled datasets.",
        tags: ["ml"]
    },
    {
        textA: "overfitting",
        textB: "underfitting",
        category: "ai_concepts",
        relation: "opposite",
        explanation: "Overfitting memorizes training data; underfitting fails to capture the underlying pattern in training data.",
        tags: ["evaluation"]
    },
    {
        textA: "training",
        textB: "inference",
        category: "ai_concepts",
        relation: "opposite",
        explanation: "Training computes model weights from data; inference runs the weighted model to make predictions.",
        tags: ["pipeline"]
    },
    {
        textA: "bias",
        textB: "fairness",
        category: "ai_concepts",
        relation: "opposite",
        explanation: "Bias represents systematic error or prejudice in a model, while fairness is the active mitigation of that bias.",
        tags: ["ethics"]
    },
    {
        textA: "dog",
        textB: "Kubernetes",
        category: "ai_concepts",
        relation: "unrelated",
        explanation: "A dog is a canine animal; Kubernetes is a cloud system container orchestration tool.",
        tags: ["mismatch"]
    },

    // === Category: Job Search ===
    {
        textA: "resume",
        textB: "CV",
        category: "job_search",
        relation: "very_similar",
        explanation: "Resume and CV (Curriculum Vitae) are terms for documents detailing professional history.",
        tags: ["career"]
    },
    {
        textA: "Java backend developer",
        textB: "Spring Boot engineer",
        category: "job_search",
        relation: "very_similar",
        explanation: "A Spring Boot engineer is highly likely to be classified as a Java backend developer.",
        tags: ["roles"]
    },
    {
        textA: "job search",
        textB: "career search",
        category: "job_search",
        relation: "very_similar",
        explanation: "Job search and career search represent the process of looking for employment.",
        tags: ["hiring"]
    },
    {
        textA: "salary",
        textB: "compensation package",
        category: "job_search",
        relation: "very_similar",
        explanation: "Salary is the core base pay component within an overall compensation package.",
        tags: ["offers"]
    },
    {
        textA: "recruiter",
        textB: "talent acquisition",
        category: "job_search",
        relation: "very_similar",
        explanation: "Recruiters and talent acquisition professionals specialize in sourcing candidates for jobs.",
        tags: ["recruitment"]
    },
    {
        textA: "interview",
        textB: "hiring process",
        category: "job_search",
        relation: "related",
        explanation: "An interview is a critical interactive evaluation stage within the broader hiring process.",
        tags: ["interviewing"]
    },
    {
        textA: "technical test",
        textB: "live coding",
        category: "job_search",
        relation: "related",
        explanation: "Live coding is a specific method used to conduct a technical test during developer interviews.",
        tags: ["testing"]
    },
    {
        textA: "probation period",
        textB: "onboarding",
        category: "job_search",
        relation: "related",
        explanation: "A probation period is the initial evaluation duration following employee onboarding.",
        tags: ["employment"]
    },
    {
        textA: "offer letter",
        textB: "employment contract",
        category: "job_search",
        relation: "related",
        explanation: "An offer letter outlines basic terms, which are legally finalized in the employment contract.",
        tags: ["contracts"]
    },
    {
        textA: "interview",
        textB: "confidence",
        category: "job_search",
        relation: "weakly_related",
        explanation: "Confidence is a useful personal trait during interviews, though they test concrete skills.",
        tags: ["soft_skills"]
    },
    {
        textA: "hired",
        textB: "rejected",
        category: "job_search",
        relation: "opposite",
        explanation: "Hired means being accepted for a role; rejected means being dismissed from the candidate pool.",
        tags: ["outcomes"]
    },
    {
        textA: "full-time",
        textB: "part-time",
        category: "job_search",
        relation: "opposite",
        explanation: "Full-time employees work standard hours; part-time employees work fewer hours per week.",
        tags: ["hours"]
    },
    {
        textA: "remote work",
        textB: "on-site office",
        category: "job_search",
        relation: "opposite",
        explanation: "Remote work is done from home/anywhere; on-site office requires commuting to a physical company facility.",
        tags: ["location"]
    },
    {
        textA: "junior developer",
        textB: "senior engineer",
        category: "job_search",
        relation: "opposite",
        explanation: "A junior developer is entry-level; a senior engineer is highly experienced and leads projects.",
        tags: ["experience"]
    },
    {
        textA: "soft skills",
        textB: "technical skills",
        category: "job_search",
        relation: "opposite",
        explanation: "Soft skills relate to communication and attitude; technical skills relate to coding and tools.",
        tags: ["skills"]
    },
    {
        textA: "freelancer",
        textB: "employee",
        category: "job_search",
        relation: "opposite",
        explanation: "A freelancer is self-employed across multiple contracts; an employee works directly for one employer.",
        tags: ["status"]
    },
    {
        textA: "pizza",
        textB: "database indexing",
        category: "job_search",
        relation: "unrelated",
        explanation: "Pizza is a flatbread food; database indexing is a computer science structural technique.",
        tags: ["mismatch"]
    },

    // === Category: Everyday Objects ===
    {
        textA: "car",
        textB: "vehicle",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "A car is a specific sub-class and type of vehicle.",
        tags: ["transport"]
    },
    {
        textA: "dog",
        textB: "puppy",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "A puppy is simply a young dog.",
        tags: ["animals", "pets"]
    },
    {
        textA: "cup",
        textB: "mug",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "Cups and mugs are both small vessels designed for drinking liquids.",
        tags: ["kitchen"]
    },
    {
        textA: "phone",
        textB: "smartphone",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "A smartphone is a modern category of phone equipped with internet access.",
        tags: ["tech", "devices"]
    },
    {
        textA: "television",
        textB: "TV",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "TV is the standard abbreviation for television.",
        tags: ["media"]
    },
    {
        textA: "login",
        textB: "authentication",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "Login is the action a user performs to verify identity for authentication.",
        tags: ["security"]
    },
    {
        textA: "logout",
        textB: "deauthentication",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "Logging out ends an active session, which is a deauthentication event.",
        tags: ["security"]
    },
    {
        textA: "folder",
        textB: "directory",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "Folder and directory refer to the same logical container on a filesystem.",
        tags: ["computers"]
    },
    {
        textA: "URL",
        textB: "web address",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "A URL (Uniform Resource Locator) is the technical name for a web address.",
        tags: ["internet"]
    },
    {
        textA: "SSL",
        textB: "TLS",
        category: "everyday_objects",
        relation: "very_similar",
        explanation: "TLS is the updated cryptographic successor to SSL, though often referred to as SSL.",
        tags: ["security", "networking"]
    },
    {
        textA: "house",
        textB: "apartment",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are physical places of residence, though houses are detached and apartments are clustered.",
        tags: ["housing"]
    },
    {
        textA: "bicycle",
        textB: "motorcycle",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are two-wheeled vehicles, but motorcycles have combustion or electric motors.",
        tags: ["transport"]
    },
    {
        textA: "chair",
        textB: "table",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are standard furniture items commonly used together in dining or workspaces.",
        tags: ["furniture"]
    },
    {
        textA: "pen",
        textB: "pencil",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are handheld utensils used for writing or drawing on paper.",
        tags: ["writing"]
    },
    {
        textA: "key",
        textB: "lock",
        category: "everyday_objects",
        relation: "related",
        explanation: "A physical key is inserted into a lock mechanism to open it.",
        tags: ["security"]
    },
    {
        textA: "shoes",
        textB: "socks",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are worn on the feet, with socks typically layered beneath shoes.",
        tags: ["clothing"]
    },
    {
        textA: "clock",
        textB: "watch",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both display the time; a watch is worn on the wrist, a clock is mounted or freestanding.",
        tags: ["time"]
    },
    {
        textA: "window",
        textB: "door",
        category: "everyday_objects",
        relation: "related",
        explanation: "Both are structures built into walls; doors are for entry/exit, windows are for light/ventilation.",
        tags: ["buildings"]
    },
    {
        textA: "book",
        textB: "e-reader",
        category: "everyday_objects",
        relation: "related",
        explanation: "An e-reader is a digital device used to read electronic versions of books.",
        tags: ["reading"]
    },
    {
        textA: "mirror",
        textB: "reflection",
        category: "everyday_objects",
        relation: "related",
        explanation: "A mirror is a reflective surface that bounces light to show a reflection.",
        tags: ["objects"]
    },
    {
        textA: "monitoring",
        textB: "Datadog",
        category: "everyday_objects",
        relation: "related",
        explanation: "Datadog is a popular software service used for systems monitoring.",
        tags: ["devops", "datadog"]
    },
    {
        textA: "cache",
        textB: "Redis",
        category: "everyday_objects",
        relation: "related",
        explanation: "Redis is one of the most prominent databases used to implement memory caches.",
        tags: ["databases", "caching"]
    },
    {
        textA: "frontend",
        textB: "React",
        category: "everyday_objects",
        relation: "related",
        explanation: "React is a dominant JavaScript framework used to build modern frontend UIs.",
        tags: ["frontend", "web"]
    },
    {
        textA: "backend",
        textB: "API",
        category: "everyday_objects",
        relation: "related",
        explanation: "Backend applications are responsible for constructing and exposing APIs to clients.",
        tags: ["backend", "api"]
    },
    {
        textA: "Docker",
        textB: "Kubernetes",
        category: "everyday_objects",
        relation: "related",
        explanation: "Docker packages code in containers; Kubernetes coordinates those containers across clusters.",
        tags: ["devops", "containers"]
    },
    {
        textA: "apartment",
        textB: "furniture",
        category: "everyday_objects",
        relation: "weakly_related",
        explanation: "Apartments contain furniture, but they represent entirely separate physical entities.",
        tags: ["housing"]
    },
    {
        textA: "flight",
        textB: "airport",
        category: "everyday_objects",
        relation: "weakly_related",
        explanation: "Flights originate from airports, representing different components of air travel.",
        tags: ["aviation"]
    },
    {
        textA: "camera",
        textB: "photo",
        category: "everyday_objects",
        relation: "weakly_related",
        explanation: "A camera is the hardware device used to capture or record a photograph.",
        tags: ["photography"]
    },
    {
        textA: "open",
        textB: "closed",
        category: "everyday_objects",
        relation: "opposite",
        explanation: "Open and closed are binary opposite physical or logical states.",
        tags: ["states"]
    },
    {
        textA: "light",
        textB: "dark",
        category: "everyday_objects",
        relation: "opposite",
        explanation: "Light refers to illumination; dark represents the absence of light.",
        tags: ["optics"]
    },
    {
        textA: "sofa",
        textB: "CI/CD pipeline",
        category: "everyday_objects",
        relation: "unrelated",
        explanation: "A sofa is a piece of furniture for sitting; a CI/CD pipeline automates code deployment.",
        tags: ["mismatch"]
    },

    // === Category: Animals ===
    {
        textA: "cat",
        textB: "kitten",
        category: "animals",
        relation: "very_similar",
        explanation: "A kitten is a baby cat.",
        tags: ["pets", "animals"]
    },
    {
        textA: "horse",
        textB: "pony",
        category: "animals",
        relation: "very_similar",
        explanation: "A pony is a small horse breed, closely related to horses.",
        tags: ["animals"]
    },
    {
        textA: "lion",
        textB: "tiger",
        category: "animals",
        relation: "related",
        explanation: "Lions and tigers are both large apex predators in the Felidae family.",
        tags: ["wildlife"]
    },
    {
        textA: "bird",
        textB: "feather",
        category: "animals",
        relation: "related",
        explanation: "Feathers are the defining biological plumage covering birds.",
        tags: ["biology"]
    },
    {
        textA: "fish",
        textB: "shark",
        category: "animals",
        relation: "related",
        explanation: "Sharks are a cartilaginous species of large predatory fish.",
        tags: ["marine"]
    },
    {
        textA: "elephant",
        textB: "mammal",
        category: "animals",
        relation: "related",
        explanation: "An elephant is the largest living terrestrial mammal.",
        tags: ["wildlife"]
    },
    {
        textA: "bee",
        textB: "honey",
        category: "animals",
        relation: "related",
        explanation: "Honeybees collect nectar to produce honey inside their hives.",
        tags: ["insects"]
    },
    {
        textA: "wolf",
        textB: "dog",
        category: "animals",
        relation: "related",
        explanation: "Dogs are domesticated species that share direct ancestry with wild wolves.",
        tags: ["canines"]
    },
    {
        textA: "reptile",
        textB: "amphibian",
        category: "animals",
        relation: "related",
        explanation: "Both are cold-blooded vertebrates, though amphibians split time between water and land.",
        tags: ["herpetology"]
    },
    {
        textA: "bear",
        textB: "hibernation",
        category: "animals",
        relation: "related",
        explanation: "Many bear species undergo a prolonged winter sleep state called hibernation.",
        tags: ["biology"]
    },
    {
        textA: "whale",
        textB: "dolphin",
        category: "animals",
        relation: "related",
        explanation: "Whales and dolphins are both highly intelligent aquatic mammals (cetaceans).",
        tags: ["marine"]
    },
    {
        textA: "cow",
        textB: "milk",
        category: "animals",
        relation: "related",
        explanation: "Dairy cows are bred and kept on farms to produce milk for human consumption.",
        tags: ["farming"]
    },
    {
        textA: "sheep",
        textB: "wool",
        category: "animals",
        relation: "related",
        explanation: "Sheep are domestic animals sheared annually for their wool coat.",
        tags: ["farming"]
    },
    {
        textA: "eagle",
        textB: "hawk",
        category: "animals",
        relation: "related",
        explanation: "Eagles and hawks are both diurnal birds of prey in the Accipitridae family.",
        tags: ["birds"]
    },
    {
        textA: "spider",
        textB: "insect",
        category: "animals",
        relation: "weakly_related",
        explanation: "Spiders are arachnids, which are separate from insects, but both are small invertebrates.",
        tags: ["invertebrates"]
    },
    {
        textA: "toothbrush",
        textB: "vector database",
        category: "animals",
        relation: "unrelated",
        explanation: "A toothbrush cleans teeth; a vector database stores floating-point embeddings.",
        tags: ["mismatch"]
    },

    // === Category: Food ===
    {
        textA: "pizza",
        textB: "food",
        category: "food",
        relation: "very_similar",
        explanation: "Pizza is a globally popular dish classified under food.",
        tags: ["meals"]
    },
    {
        textA: "apple",
        textB: "fruit",
        category: "food",
        relation: "very_similar",
        explanation: "An apple is a specific variety of tree fruit.",
        tags: ["produce"]
    },
    {
        textA: "water",
        textB: "beverage",
        category: "food",
        relation: "very_similar",
        explanation: "Water is the basic chemical substance consumed as a beverage.",
        tags: ["liquids"]
    },
    {
        textA: "sugar",
        textB: "sweetener",
        category: "food",
        relation: "very_similar",
        explanation: "Granulated sugar is the primary refined substance used as a sweetener.",
        tags: ["cooking"]
    },
    {
        textA: "vegetable",
        textB: "carrot",
        category: "food",
        relation: "very_similar",
        explanation: "A carrot is a root vegetable.",
        tags: ["produce"]
    },
    {
        textA: "rice",
        textB: "grain",
        category: "food",
        relation: "very_similar",
        explanation: "Rice is a staple cereal grass seed classified as a grain.",
        tags: ["staples"]
    },
    {
        textA: "dessert",
        textB: "cake",
        category: "food",
        relation: "very_similar",
        explanation: "Cake is a sweet baked food typically served as a dessert.",
        tags: ["sweets"]
    },
    {
        textA: "cheese",
        textB: "dairy",
        category: "food",
        relation: "very_similar",
        explanation: "Cheese is a concentrated food product made from coagulated dairy milk.",
        tags: ["dairy"]
    },
    {
        textA: "bread",
        textB: "toast",
        category: "food",
        relation: "related",
        explanation: "Toast is sliced bread that has been browned by exposure to radiant heat.",
        tags: ["bakery"]
    },
    {
        textA: "coffee",
        textB: "tea",
        category: "food",
        relation: "related",
        explanation: "Coffee and tea are the two most popular caffeinated hot brews in the world.",
        tags: ["beverages"]
    },
    {
        textA: "salt",
        textB: "pepper",
        category: "food",
        relation: "related",
        explanation: "Salt and black pepper are the standard pairing of table condiments.",
        tags: ["seasonings"]
    },
    {
        textA: "beef",
        textB: "chicken",
        category: "food",
        relation: "related",
        explanation: "Beef and chicken are two of the most common animal meats eaten.",
        tags: ["meat"]
    },
    {
        textA: "butter",
        textB: "margarine",
        category: "food",
        relation: "related",
        explanation: "Margarine is a highly processed vegetable oil emulsion used to replace butter.",
        tags: ["spreads"]
    },
    {
        textA: "soup",
        textB: "broth",
        category: "food",
        relation: "related",
        explanation: "Broth is the flavored liquid base obtained by simmering ingredients for soup.",
        tags: ["cooking"]
    },
    {
        textA: "wine",
        textB: "beer",
        category: "food",
        relation: "related",
        explanation: "Wine and beer are both fermented alcoholic beverages made from grapes and grains respectively.",
        tags: ["alcohol"]
    },
    {
        textA: "soup",
        textB: "GitHub Actions",
        category: "food",
        relation: "unrelated",
        explanation: "Soup is a warm liquid food; GitHub Actions is a cloud CI/CD execution service.",
        tags: ["mismatch"]
    },

    // === Category: Geography ===
    {
        textA: "country",
        textB: "nation",
        category: "geography",
        relation: "very_similar",
        explanation: "Country and nation are terms referring to an independent sovereign territory.",
        tags: ["politics"]
    },
    {
        textA: "city",
        textB: "town",
        category: "geography",
        relation: "related",
        explanation: "Cities and towns are urban human settlements, but cities are generally larger and denser.",
        tags: ["settlements"]
    },
    {
        textA: "river",
        textB: "lake",
        category: "geography",
        relation: "related",
        explanation: "Rivers are flowing bodies of fresh water; lakes are static bodies of water enclosed by land.",
        tags: ["water"]
    },
    {
        textA: "ocean",
        textB: "sea",
        category: "geography",
        relation: "related",
        explanation: "Seas are smaller bodies of salt water, often partially bordered by land, feeding into oceans.",
        tags: ["marine"]
    },
    {
        textA: "map",
        textB: "globe",
        category: "geography",
        relation: "related",
        explanation: "A map is a flat representation of geographic areas; a globe is a spherical model of Earth.",
        tags: ["tools"]
    },
    {
        textA: "capital",
        textB: "city",
        category: "geography",
        relation: "related",
        explanation: "A capital is a city that serves as the official seat of government for a country.",
        tags: ["settlements"]
    },
    {
        textA: "beach",
        textB: "coast",
        category: "geography",
        relation: "related",
        explanation: "Beaches are sandy shorelines located along a coastal region.",
        tags: ["landforms"]
    },
    {
        textA: "glacier",
        textB: "iceberg",
        category: "geography",
        relation: "related",
        explanation: "Icebergs are large chunks of freshwater ice that calved off glaciers and float in open water.",
        tags: ["ice"]
    },
    {
        textA: "volcano",
        textB: "lava",
        category: "geography",
        relation: "related",
        explanation: "Volcanoes are crust ruptures that erupt molten rock called lava.",
        tags: ["geology"]
    },
    {
        textA: "mountain",
        textB: "valley",
        category: "geography",
        relation: "opposite",
        explanation: "Mountains are high geological elevations; valleys are low areas nestled between hills or mountains.",
        tags: ["landforms"]
    },
    {
        textA: "continent",
        textB: "island",
        category: "geography",
        relation: "opposite",
        explanation: "Continents are massive continuous landmasses; islands are smaller lands surrounded entirely by water.",
        tags: ["landforms"]
    },
    {
        textA: "north",
        textB: "south",
        category: "geography",
        relation: "opposite",
        explanation: "North and south are polar opposite directions on a compass.",
        tags: ["directions"]
    },
    {
        textA: "east",
        textB: "west",
        category: "geography",
        relation: "opposite",
        explanation: "East and west are opposite orthogonal directions on a compass.",
        tags: ["directions"]
    },
    {
        textA: "desert",
        textB: "rainforest",
        category: "geography",
        relation: "opposite",
        explanation: "Deserts are arid biomes with very low rainfall; rainforests are dense wet biomes with high rainfall.",
        tags: ["biomes"]
    },
    {
        textA: "equator",
        textB: "pole",
        category: "geography",
        relation: "opposite",
        explanation: "The equator is the warmest zero-latitude belt; the poles represent the coldest high-latitude points.",
        tags: ["latitudes"]
    },
    {
        textA: "mountain",
        textB: "authentication token",
        category: "geography",
        relation: "unrelated",
        explanation: "A mountain is a large natural land elevation; an authentication token is a digital security string.",
        tags: ["mismatch"]
    },

    // === Category: Opposite Concepts ===
    {
        textA: "hot",
        textB: "cold",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Hot and cold represent opposite extremes of thermal energy.",
        tags: ["physics"]
    },
    {
        textA: "fast",
        textB: "slow",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Fast and slow indicate opposite speeds of velocity or motion.",
        tags: ["motion"]
    },
    {
        textA: "success",
        textB: "failure",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Success indicates the accomplishment of an aim; failure is the lack of success.",
        tags: ["outcomes"]
    },
    {
        textA: "increase",
        textB: "decrease",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Increase refers to growth in quantity; decrease is a reduction in size or quantity.",
        tags: ["trends"]
    },
    {
        textA: "public",
        textB: "private",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Public signifies open access to all; private restricts access to authorized users.",
        tags: ["access"]
    },
    {
        textA: "similar",
        textB: "different",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Similar describes things sharing characteristics; different describes distinct elements.",
        tags: ["comparison"]
    },
    {
        textA: "online",
        textB: "offline",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Online means active network connectivity; offline represents a disconnected state.",
        tags: ["networks"]
    },
    {
        textA: "enabled",
        textB: "disabled",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Enabled indicates an active state ready for use; disabled is inactive and turned off.",
        tags: ["settings"]
    },
    {
        textA: "accept",
        textB: "reject",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Accept is to receive or agree to; reject is to decline or throw away.",
        tags: ["actions"]
    },
    {
        textA: "high",
        textB: "low",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "High and low denote opposite positions or magnitudes along a vertical scale.",
        tags: ["scale"]
    },
    {
        textA: "rich",
        textB: "poor",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Rich implies abundant wealth or assets; poor denotes the lack of financial resources.",
        tags: ["economics"]
    },
    {
        textA: "true",
        textB: "false",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "True and false are the two opposite binary states of Boolean logic.",
        tags: ["logic"]
    },
    {
        textA: "love",
        textB: "hate",
        category: "opposite_concepts",
        relation: "opposite",
        explanation: "Love is deep affection; hate is intense aversion or hostility.",
        tags: ["emotions"]
    },
    {
        textA: "guitar",
        textB: "BigQuery",
        category: "opposite_concepts",
        relation: "unrelated",
        explanation: "A guitar is an acoustic stringed instrument; BigQuery is a serverless Google database.",
        tags: ["mismatch"]
    },

    // === Category: Weakly Related ===
    {
        textA: "coffee",
        textB: "productivity",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Coffee contains caffeine which can stimulate temporary focus and improve work productivity.",
        tags: ["lifestyle"]
    },
    {
        textA: "train",
        textB: "office",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Trains are a transit system that workers use to commute to physical offices.",
        tags: ["transit"]
    },
    {
        textA: "book",
        textB: "library",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Libraries house collections of books, but they serve as community centers and digital hubs too.",
        tags: ["buildings"]
    },
    {
        textA: "interview",
        textB: "resume",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Resumes are submitted to apply for jobs, which may lead to interviews, representing distinct steps.",
        tags: ["career"]
    },
    {
        textA: "coffee",
        textB: "programming",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Many programmers drink coffee to keep focused, although there is no technical relation to writing code.",
        tags: ["lifestyle"]
    },
    {
        textA: "sleep",
        textB: "dream",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Dreams occur during sleep stages, though sleep is a vital restorative biological process.",
        tags: ["biology"]
    },
    {
        textA: "music",
        textB: "relaxation",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Listening to music can assist in stress relief, though music can also be intense and loud.",
        tags: ["health"]
    },
    {
        textA: "exercise",
        textB: "health",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Regular physical exercise is one of many contributing inputs to general human health.",
        tags: ["lifestyle"]
    },
    {
        textA: "money",
        textB: "happiness",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Money reduces material stress, but psychological research shows it has weak correlation with raw happiness.",
        tags: ["philosophy"]
    },
    {
        textA: "sun",
        textB: "sunscreen",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Sunscreen is applied to the skin to block ultraviolet radiation emitted by the sun.",
        tags: ["protection"]
    },
    {
        textA: "vector",
        textB: "graph",
        category: "weakly_related",
        relation: "weakly_related",
        explanation: "Vectors and graphs are mathematical objects used for structures, but in different domains.",
        tags: ["math"]
    },

    // === Category: Unrelated Concepts ===
    {
        textA: "pizza",
        textB: "database indexing",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Pizza is a flatbread dish; database indexing is a storage retrieval acceleration technique.",
        tags: ["unrelated"]
    },
    {
        textA: "dog",
        textB: "Kubernetes",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A dog is a household animal; Kubernetes is a software system container orchestrator.",
        tags: ["unrelated"]
    },
    {
        textA: "beach",
        textB: "Java exception",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A beach is a coastal geological deposit; a Java exception is a language runtime error.",
        tags: ["unrelated"]
    },
    {
        textA: "football",
        textB: "SQL query",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Football is an outdoor field sport; an SQL query is a relational database statement.",
        tags: ["unrelated"]
    },
    {
        textA: "banana",
        textB: "cloud deployment",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A banana is an tropical fruit; cloud deployment is the uploading of server code.",
        tags: ["unrelated"]
    },
    {
        textA: "toothbrush",
        textB: "vector database",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A toothbrush is a personal cleaning brush; a vector database indexes math embeddings.",
        tags: ["unrelated"]
    },
    {
        textA: "sofa",
        textB: "CI/CD pipeline",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A sofa is seating furniture; a CI/CD pipeline compiles, tests, and deploys code.",
        tags: ["unrelated"]
    },
    {
        textA: "mountain",
        textB: "authentication token",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A mountain is a natural geographic landmass; an authentication token is a digital security key.",
        tags: ["unrelated"]
    },
    {
        textA: "soup",
        textB: "GitHub Actions",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Soup is a cooked liquid food; GitHub Actions is an automation workflow runner.",
        tags: ["unrelated"]
    },
    {
        textA: "guitar",
        textB: "BigQuery",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A guitar is a musical instrument; BigQuery is a massive Google data warehouse system.",
        tags: ["unrelated"]
    },
    {
        textA: "astronaut",
        textB: "frying pan",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "An astronaut is a space traveler; a frying pan is a kitchen cooking tool.",
        tags: ["unrelated"]
    },
    {
        textA: "helicopter",
        textB: "strawberry",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A helicopter is an aircraft; a strawberry is an aggregate red fruit.",
        tags: ["unrelated"]
    },
    {
        textA: "submarines",
        textB: "cheesecake",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Submarines are deep-sea naval vessels; cheesecake is a sweet layered dessert.",
        tags: ["unrelated"]
    },
    {
        textA: "microscope",
        textB: "popcorn",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A microscope is scientific magnification equipment; popcorn is a heated snack food.",
        tags: ["unrelated"]
    },
    {
        textA: "volleyball",
        textB: "compiler error",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Volleyball is an athletic net sport; a compiler error is an syntax bug in programming.",
        tags: ["unrelated"]
    },
    {
        textA: "koala",
        textB: "docker-compose",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A koala is an Australian arboreal mammal; docker-compose is a local container scripting utility.",
        tags: ["unrelated"]
    },
    {
        textA: "kangaroo",
        textB: "JSON Web Token",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A kangaroo is an Australian marsupial; a JSON Web Token is a web standard encoding format.",
        tags: ["unrelated"]
    },
    {
        textA: "tacos",
        textB: "recursion",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Tacos are a Mexican food; recursion is a method of programming where a function calls itself.",
        tags: ["unrelated"]
    },
    {
        textA: "giraffe",
        textB: "load balancer",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A giraffe is a tall African mammal; a load balancer is networking hardware/software.",
        tags: ["unrelated"]
    },
    {
        textA: "penguin",
        textB: "binary search",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A penguin is a flightless marine bird; binary search is a logarithmic lookup algorithm.",
        tags: ["unrelated"]
    },
    {
        textA: "spaghetti",
        textB: "TypeORM",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "Spaghetti is a long, thin pasta; TypeORM is a database object-relational mapping library.",
        tags: ["unrelated"]
    },
    {
        textA: "ocean",
        textB: "CSS grid",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "An ocean is a vast body of saltwater; CSS grid is a two-dimensional layout model for websites.",
        tags: ["unrelated"]
    },
    {
        textA: "bicycle",
        textB: "garbage collector",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A bicycle is a human-powered vehicle; a garbage collector is an automatic memory management routine.",
        tags: ["unrelated"]
    },
    {
        textA: "clock",
        textB: "neural network",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A clock tracks time; a neural network is an artificial intelligence processing design.",
        tags: ["unrelated"]
    },
    {
        textA: "hamburger",
        textB: "recursion",
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: "A hamburger is a sandwich; recursion is a programming pattern where functions reference themselves.",
        tags: ["unrelated"]
    },

    // === Category: Spelling Similar, Meaning Different ===
    {
        textA: "Java",
        textB: "JavaScript",
        category: "spelling_similar_meaning_different",
        relation: "weakly_related",
        explanation: "Java and JavaScript are two completely different programming languages with different runtimes, syntax, and history, despite the shared 'Java' prefix.",
        tags: ["spelling", "languages"]
    },
    {
        textA: "React",
        textB: "reactor",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "React is a JavaScript UI framework, while a reactor is a device for chemical or nuclear reactions. They are semantically unrelated.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "cache",
        textB: "cash",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "Cache is a temporary data storage layer, while cash is physical currency. They are homophones but have entirely different meanings.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "token",
        textB: "taken",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A token is a designator of value or access; 'taken' is the past participle of 'take'. They differ by one character.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "model",
        textB: "modal",
        category: "spelling_similar_meaning_different",
        relation: "weakly_related",
        explanation: "A model is a representation of data or system logic; a modal is a pop-up window in frontend design.",
        tags: ["spelling"]
    },
    {
        textA: "route",
        textB: "root",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A route is a path for request routing; a root is the base level of a directory or tree hierarchy. They look and sound similar but mean different things.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "server",
        textB: "sever",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A server is a software system hosting data; to sever means to cut or separate. They differ by a single character.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "SQL",
        textB: "sequel",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "SQL is a database query language, while a sequel is a continuation of a story. Although pronounced similarly, their meanings are unrelated.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "cloud",
        textB: "clout",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "Cloud refers to remote computer servers or water vapor; clout means social influence or power. They differ by a single letter.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "docker",
        textB: "doctor",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "Docker is a containerization software platform; a doctor is a medical health professional.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "array",
        textB: "arrow",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "An array is a data structure for elements; an arrow is a directional symbol or projectile. They are spelled similarly but have unrelated meanings.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "class",
        textB: "glass",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A class is an OOP programming template or category; glass is a brittle transparent material. They differ by the first letter.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "byte",
        textB: "bite",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A byte is 8 bits of digital data; a bite is an action of using teeth. They are homophones but completely unrelated.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "queue",
        textB: "cue",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A queue is a FIFO data structure or line; a cue is a signal to start or a pool stick. They are homophones with distinct meanings.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "bug",
        textB: "bag",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A bug is a coding defect or insect; a bag is a flexible container. Only the vowel is different.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "commit",
        textB: "comet",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A commit is a save point in Git or databases; a comet is a celestial body orbiting the sun. Spelled similarly but unrelated.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "merge",
        textB: "emerge",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "To merge is to combine branches or datasets; to emerge is to come into view. They sound similar but describe different processes.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "branch",
        textB: "brunch",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A branch is a Git code history line or wood limb; brunch is a late morning meal. They differ by a single vowel.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "deploy",
        textB: "display",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "To deploy is to ship software applications; to display is to show pixels on a screen. Both are common tech verbs but unrelated.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "schema",
        textB: "scheme",
        category: "spelling_similar_meaning_different",
        relation: "weakly_related",
        explanation: "A schema is a structured layout for database tables; a scheme is a plan or proposal. They share origin roots but are distinct in tech.",
        tags: ["spelling"]
    },
    {
        textA: "index",
        textB: "indie",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "An index is a database lookup structure; indie is independent media, music, or game developers. They look and sound similar.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "vector",
        textB: "victor",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A vector is a high-dimensional mathematical array; a victor is a winner or champion. Spelled almost identically.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "cosine",
        textB: "cousin",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "Cosine is a trigonometric function representing angles; a cousin is a relative. They share sounds and letters but have no semantic overlap.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "node",
        textB: "note",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "A node is a connection point in a graph network; a note is a brief record or musical sound. They differ by a single character.",
        tags: ["spelling", "mismatch"]
    },
    {
        textA: "spring",
        textB: "string",
        category: "spelling_similar_meaning_different",
        relation: "unrelated",
        explanation: "Spring is a season, coil, or Java framework; a string is a sequence of characters. They differ by only one character.",
        tags: ["spelling", "mismatch"]
    }
];

// Helper to generate the remaining ~120+ pairs dynamically to hit the 220+ requirement programmatically.
// This guarantees we have a large robust list of examples, while keeping the source file size clean.
// We compile them deterministically at module import.
const additionalGeneratedExamples: DemoExample[] = [];

// Arrays of concepts for programmatic pair generation to ensure 220+ total size.
// Category: RAG & Vector Search
const ragA = ["dense embeddings", "LlamaIndex", "semantic similarity", "context retrieval", "neural search", "ANN search", "cross-encoder"];
const ragB = ["sparse embeddings", "LangChain", "lexical similarity", "prompt generation", "keyword lookup", "exact matching", "bi-encoder"];
const ragExplanations = [
    "Dense and sparse embeddings represent different structural representations of texts.",
    "LlamaIndex and LangChain are competitive orchestration frameworks for LLM application building.",
    "Semantic similarity focuses on conceptual meaning, while lexical similarity focuses on matching exact words.",
    "Context retrieval fetches documents, and prompt generation formats them into query text.",
    "Neural search uses deep learning, whereas keyword lookup searches exact strings.",
    "Approximate Nearest Neighbor (ANN) search computes approximate similarity faster than exact matching.",
    "Cross-encoders process pairs together, while bi-encoders compute vector embeddings separately."
];

for (let i = 0; i < ragA.length; i++) {
    additionalGeneratedExamples.push({
        textA: ragA[i],
        textB: ragB[i],
        category: "rag_vector_search",
        relation: i === 1 || i === 3 ? "related" : (i === 0 || i === 2 || i === 4 || i === 6 ? "opposite" : "weakly_related"),
        explanation: ragExplanations[i]
    });
}

// Category: Software Development
const devA = ["compilation", "object-oriented", "imperative programming", "monolithic code", "manual memory", "strong typing"];
const devB = ["decompilation", "functional programming", "declarative programming", "serverless code", "garbage collection", "weak typing"];
const devExplanations = [
    "Compilation turns source into machine code; decompilation attempts the reverse.",
    "Object-oriented programming uses classes/objects, while functional programming uses pure functions.",
    "Imperative programming details how to perform actions, while declarative programming details what is desired.",
    "Monolithic code runs as a single unit, serverless code runs as ephemeral decoupled functions.",
    "Manual memory requires malloc/free; garbage collection automatically reclaims unused RAM.",
    "Strong typing prevents implicit conversions, whereas weak typing performs automatic conversions."
];

for (let i = 0; i < devA.length; i++) {
    additionalGeneratedExamples.push({
        textA: devA[i],
        textB: devB[i],
        category: "software_development",
        relation: "opposite",
        explanation: devExplanations[i]
    });
}

// Category: Databases
const dbA = ["relational schema", "horizontal scaling", "index scan", "pessimistic locking", "SQL database", "ACID guarantees", "data warehouse"];
const dbB = ["schemaless structure", "vertical scaling", "sequential scan", "optimistic locking", "graph database", "BASE guarantees", "data lake"];
const dbExplanations = [
    "Relational schemas define structured columns; schemaless structures store dynamic arbitrary documents.",
    "Horizontal scaling adds more machine nodes; vertical scaling adds RAM/CPU to a single machine.",
    "Index scans use trees to locate rows; sequential scans read through the entire table.",
    "Pessimistic locking blocks writes ahead; optimistic locking checks for conflicts at commit time.",
    "SQL databases store tabular rows; graph databases store nodes and relationship edges.",
    "ACID prioritizes strict consistency; BASE prioritizes eventual availability.",
    "A data warehouse stores structured, processed data; a data lake stores raw, unstructured data."
];

for (let i = 0; i < dbA.length; i++) {
    additionalGeneratedExamples.push({
        textA: dbA[i],
        textB: dbB[i],
        category: "databases",
        relation: "opposite",
        explanation: dbExplanations[i]
    });
}

// Category: Cloud & DevOps
const cloudA = ["infrastructure", "container image", "virtual machine", "load balancer", "production environment"];
const cloudB = ["application code", "running container", "bare metal hardware", "reverse proxy", "staging environment"];
const cloudExplanations = [
    "Infrastructure hosts the hardware and environments; application code runs on top of it.",
    "A container image is a static snapshot; a running container is the active instance of that image.",
    "Virtual machines run virtualized OS hypervisors; bare metal is the raw physical hardware.",
    "Load balancers distribute incoming requests; reverse proxies route/manage requests for backend servers.",
    "Production environments host live customer traffic; staging environments host internal release tests."
];

for (let i = 0; i < cloudA.length; i++) {
    additionalGeneratedExamples.push({
        textA: cloudA[i],
        textB: cloudB[i],
        category: "cloud_devops",
        relation: "related",
        explanation: cloudExplanations[i]
    });
}

// Category: AI Concepts
const aiA = ["neural networks", "transformer model", "encoder", "training loss", "artificial intelligence", "generative model", "reinforcement learning"];
const aiB = ["perceptron layers", "attention mechanism", "decoder", "validation loss", "data science", "discriminative model", "genetic algorithm"];
const aiExplanations = [
    "Neural networks are multi-layer structures, which evolved from simple single-layer perceptrons.",
    "Transformer models rely on self-attention mechanisms to compute relationships between words.",
    "Encoders process input text into vectors; decoders unpack vectors back into generated text.",
    "Training loss measures errors on training data; validation loss measures errors on unseen validation sets.",
    "Artificial intelligence is the broad field of smart machines; data science is the statistical study of data.",
    "Generative models synthesize new data samples; discriminative models classify existing data samples.",
    "Reinforcement learning uses reward feedbacks; genetic algorithms use evolutionary selections."
];

for (let i = 0; i < aiA.length; i++) {
    additionalGeneratedExamples.push({
        textA: aiA[i],
        textB: aiB[i],
        category: "ai_concepts",
        relation: i === 4 ? "related" : "opposite",
        explanation: aiExplanations[i]
    });
}

// Generate cross-category unrelated examples programmatically to ensure we hit a high count
const unrelatedWordsA = [
    "elephant", "sunflower", "keyboard", "submarine", "spaghetti",
    "jupiter", "microscope", "avocado", "origami", "lighthouse",
    "saxophone", "thermometer", "umbrella", "skateboard", "crocodile",
    "helicopter", "kangaroo", "waterfall", "volcano", "telescope",
    "sushi", "chocolate", "guitar", "sandwich", "astronaut",
    "cactus", "penguin", "diamond", "cushion", "backpack"
];

const unrelatedWordsB = [
    "git merge", "SQL query", "container registry", "prompt engineering", "API gateway",
    "CSS flexbox", "JWT token", "TypeORM entity", "HNSW graph", "Docker daemon",
    "Redis cache", "Kubernetes pod", "lambda function", "semantic search", "vector database",
    "load balancer", "binary search", "garbage collector", "microservice", "OAuth flow",
    "CI pipeline", "JSON schema", "web socket", "git commit", "HTTP request",
    "npm package", "TypeScript compiler", "unit test", "Webpack config", "env variable"
];

for (let i = 0; i < unrelatedWordsA.length; i++) {
    additionalGeneratedExamples.push({
        textA: unrelatedWordsA[i],
        textB: unrelatedWordsB[i],
        category: "unrelated_concepts",
        relation: "unrelated",
        explanation: `The concept of '${unrelatedWordsA[i]}' has absolutely no logical connection to '${unrelatedWordsB[i]}'.`,
        tags: ["unrelated"]
    });
}

// Generate simple everyday objects & concepts to flesh out related/unrelated
const objA = [
    "apartment", "flight", "classroom", "hospital", "movie",
    "restaurant", "raincoat", "refrigerator", "wallet", "furnace"
];
const objB = [
    "tenant", "boarding pass", "teacher", "patient", "popcorn",
    "waiter", "umbrella", "freezer", "credit card", "thermostat"
];
for (let i = 0; i < objA.length; i++) {
    additionalGeneratedExamples.push({
        textA: objA[i],
        textB: objB[i],
        category: "everyday_objects",
        relation: "related",
        explanation: `A '${objA[i]}' is closely related to a '${objB[i]}' in everyday usage and contexts.`,
        tags: ["everyday"]
    });
}

// Generate opposites
const oppA = [
    "heavy", "clean", "loud", "sharp", "thick",
    "hard", "brave", "bright", "dry", "sweet",
    "near", "early", "empty", "safe", "smooth",
    "strong", "young", "wise", "funny", "honest"
];
const oppB = [
    "light", "dirty", "quiet", "dull", "thin",
    "soft", "cowardly", "dim", "wet", "sour",
    "far", "late", "full", "dangerous", "rough",
    "weak", "old", "foolish", "serious", "deceitful"
];
for (let i = 0; i < oppA.length; i++) {
    additionalGeneratedExamples.push({
        textA: oppA[i],
        textB: oppB[i],
        category: "opposite_concepts",
        relation: "opposite",
        explanation: `'${oppA[i]}' and '${oppB[i]}' represent polar opposite adjectives.`,
        tags: ["opposites"]
    });
}

// Generate animals
const animalA = ["lion", "eagle", "crocodile", "bear", "monkey"];
const animalB = ["savannah", "nest", "swamp", "cave", "jungle"];
for (let i = 0; i < animalA.length; i++) {
    additionalGeneratedExamples.push({
        textA: animalA[i],
        textB: animalB[i],
        category: "animals",
        relation: "related",
        explanation: `A '${animalA[i]}' resides in or is associated with a '${animalB[i]}'.`,
        tags: ["animals"]
    });
}

// Generate food
const foodA = ["coffee", "hamburger", "spaghetti", "sushi", "pancake"];
const foodB = ["caffeine", "fries", "meatball", "wasabi", "syrup"];
for (let i = 0; i < foodA.length; i++) {
    additionalGeneratedExamples.push({
        textA: foodA[i],
        textB: foodB[i],
        category: "food",
        relation: "related",
        explanation: `'${foodA[i]}' is commonly associated or served with '${foodB[i]}'.`,
        tags: ["food"]
    });
}

// Generate geography
const geoA = ["Japan", "Egypt", "France", "Brazil", "Australia"];
const geoB = ["Tokyo", "Cairo", "Paris", "Brasilia", "Canberra"];
for (let i = 0; i < geoA.length; i++) {
    additionalGeneratedExamples.push({
        textA: geoA[i],
        textB: geoB[i],
        category: "geography",
        relation: "very_similar",
        explanation: `'${geoB[i]}' is the political capital city of '${geoA[i]}'.`,
        tags: ["geography"]
    });
}

// Combine all raw and generated examples
export const allDemoExamples: DemoExample[] = [
    ...rawDemoExamples,
    ...additionalGeneratedExamples
];
